name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java (for Android builds, if needed)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.3'  # Use the latest stable version or match your local setup
        channel: 'stable'  # Optional: 'stable', 'beta', etc.

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests  # Optional: Add if you have tests
      run: flutter test

    - name: Build APK  # Optional: For Android release
      run: flutter build apk --release
